### PR TITLE
[WIP]Feature/subroute

### PR DESCRIPTION
**Pull request by stupidisum**
I fullfilled the first point we discussed in #45.
However, now the detail route can't be accessed and socketSync is not working.
Maybe you can help me deal with this bug because I'm not familiar with this project enough yet.

### CODE REVIEW

**Comment by stupidisum** [comment]
Try to run `:apiroute admin2/user2` and `:api user2` and make sure apiUrls are the same. The bug will reappear.

However, if you run `:apiroute device`, it's fine. So, this bug only appears in sub-routes

**Comment by michaelkrone** [comment]
Hi @stupidisum,
Cool you got it so far, I will have a look at it tomorow and comment here.

**Comment by michaelkrone** [comment]
Got a short look at it, looks good. I will dig in more later.

**Comment by stupidisum** [comment]
I think it's ok to use this sub-route alone now.

Cooperation with traditional apiroute and route needs further research.
like 
```
:route admin
:apiroute admin.user
```
is not working yet

**Pull request merged**
